name: illHouseDesign
favicon: null
layout_spectrum: 0.48944
typography_spectrum: 0.32859
title: illHouse Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#050608'
    - '#2c3433'
    - '#bfbcbb'
    - '#4babe8'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
